# Generated by Django 3.0.8 on 2020-07-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='f_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='l_price',
            field=models.IntegerField(default=0),
        ),
    ]
