# Generated by Django 3.0.8 on 2020-07-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200721_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
