# Generated by Django 3.0.8 on 2020-07-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200725_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img1',
            field=models.FileField(blank=True, upload_to='Post-pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img2',
            field=models.FileField(blank=True, upload_to='Post-pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img3',
            field=models.FileField(blank=True, upload_to='Post-pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img4',
            field=models.FileField(blank=True, upload_to='Post-pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img5',
            field=models.FileField(blank=True, upload_to='Post-pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img6',
            field=models.FileField(blank=True, upload_to='Post-pictures'),
        ),
    ]
