# Generated by Django 3.0.8 on 2020-07-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200725_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img6',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnaila',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnaily',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
