# Generated by Django 3.0.8 on 2020-07-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200727_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnaila',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnaily',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
