# Generated by Django 3.0.8 on 2020-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200727_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnaila',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnaily',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
