# Generated by Django 3.0.8 on 2020-07-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200727_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnaila',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnaily',
        ),
    ]
