# Generated by Django 3.0.8 on 2020-07-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20200727_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured',
            new_name='ahsap',
        ),
        migrations.AddField(
            model_name='post',
            name='coksatanlar',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='enyeniler',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
