# Generated by Django 3.0.8 on 2020-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200728_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ahsap_obje',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='akıl_oyunları',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='boya',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
