# Generated by Django 3.0.8 on 2020-08-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200804_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deneme_resim',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
