# Generated by Django 3.0.8 on 2020-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20200806_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='boyalar',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
